### ISSUE TITLE
mdformat-myst adds unwanted space after a header target

### ISSUE THREAD

**Issue by devmcp** [executablebooks/mdformat-myst#20]
### Describe the bug

Having installed `mdformat-myst`, when I run `mdformat` it changes

```
(my_header)=
### My Header
```

to 

```
(my_header)=

### My Header
```

which I believe it shouldn't do

### Reproduce the bug

See above

### List your environment

mdformat-myst v0.1.5

**Comment by hukkin** [comment]
Thanks for the issue!

Mdformat is consistent in that it separates all [blocks](https://spec.commonmark.org/0.30/#blocks) with an empty line. Currently, the MyST target syntax is not an exception to this rule. If you have a good reason why this should be special cased (and under what circumstances) would be nice to hear it, but at least I'm happy with the current state.

**Comment by devmcp** [comment]
As a label for the heading, I guess it just seems like it belongs with it rather than in a separate section. To me, with the space, it looks like it's part of the content of the previous section. I don't know of any other instances like this so I think it would just be a single specific exception for the case of target headers.

**Comment by devmcp** [comment]
Ah. You're right. I misunderstood how targets are used. Thanks for taking the time to enlighten me! 😄
