### ISSUE TITLE
Bug: repeated plugin conflict printed with mdformat-footnote

### ISSUE THREAD

**Issue by jamesbraza** [executablebooks/mdformat-myst#26]
### Describe the bug

**context**

```
pip install mdformat mdformat-myst mdformat-footnote
mdformat .
```

**expectation**

I expected no warnings.

**bug**

The repeated warnings get printed 10's of times:

```console
> mdformat .
Warning: Plugin conflict. More than one plugin defined a renderer for "footnote" syntax.
Warning: Plugin conflict. More than one plugin defined a renderer for "footnote_ref" syntax.
Warning: Plugin conflict. More than one plugin defined a renderer for "footnote_block" syntax.
```

**problem**

The warning should not print tens of times.

### Reproduce the bug

See above box.

### List your environment

```
markdown-it-py       2.2.0
mdformat             0.7.16
mdformat_footnote    0.1.1
mdformat_frontmatter 2.0.1
mdformat_myst        0.1.5
mdformat_tables      0.4.1
mdit-py-plugins      0.3.5
mdurl                0.1.2
pip                  23.1.2
ruamel.yaml          0.17.26
ruamel.yaml.clib     0.2.7
setuptools           65.5.0
tomli                2.0.1
```

**Comment by hukkin** [comment]
Hey, you'll need to uninstall mdformat-footnote with mdformat-myst. That version still has its own built-in footnote support. The next version is mdformat-footnote compatible, but not yet on PyPI.

**Comment by jamesbraza** [comment]
Hi @hukkin thanks for getting back. I am going to close this as resolved then, thanks again
