### ISSUE TITLE
0.2.0 is not available on pypi

### ISSUE THREAD

**Issue by powerman** [executablebooks/mdformat-myst#30]
0.2.0 is not available on pypi

**Comment by KyleKing** [comment]
Yeah, I unfortunately don't have access to resolve the authentication error. I've asked for assistance (https://github.com/orgs/executablebooks/discussions/1196#discussioncomment-10435263) and I've removed the release and tag to prevent confusion in the meantime

**Comment by MattKang** [comment]
SO CLOSE

**Comment by agoose77** [comment]
@choldgraf I think you have the creds for this?

**Comment by KyleKing** [comment]
The two maintainers are listed as @chrisjsewell and @hukkin on PyPi: https://pypi.org/project/mdformat_myst, so they may be the only ones who can provide a working token and/or add other maintainers

I'm not how organizations work and/or if there are other owners or maintainers not listed in the PyPi panel

**Comment by agoose77** [comment]
Huh, I had assumed we'd migrated all of our repos by now! I'll ping @chrisjsewell and see if he can add @choldgraf and @ebp-bot to these repos :)

**Comment by KyleKing** [comment]
Thanks! While making changes to maintainers, you may want to do the same for these:

- https://pypi.org/project/mdformat_deflist (only chrisjsewell)
- https://pypi.org/project/mdformat_footnote (both chrisjsewell and hukkin)
- https://pypi.org/project/mdformat (only hukkin)
- https://pypi.org/project/mdit-py-plugins (only chrisjsewell)
- https://pypi.org/project/mdurl (only hukkin)
- https://pypi.org/project/markdown-it-py (has chrisjsewell and edp-bot, but not choldgraf)
- https://pypi.org/project/mdformat_tables (has only edp-bot, but not choldgraf)

**Comment by KyleKing** [comment]
One more bump, do you know what could be done to resolve this issue?

**Comment by hukkin** [comment]
@KyleKing I've invited you to the project on PyPI.

**Comment by KyleKing** [comment]
Thanks @hukkin!

Unfortunately, I don’t have access admin access to update the GitHub Action Secret and I’m traveling this weekend, but I can at least publish from my laptop on Monday if needed

**Comment by hukkin** [comment]
I pushed to PyPI locally and made a PR that should address why CI wouldn't publish for @KyleKing  before.
